# Generated by Django 6.0 on 2025-12-15 23:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('communities', '0001_initial'),
        ('content', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('instructions', models.TextField(blank=True)),
                ('time_limit_minutes', models.PositiveIntegerField(blank=True, help_text='Time limit in minutes (null = no limit)', null=True)),
                ('max_attempts', models.PositiveIntegerField(default=0, help_text='Maximum number of attempts (0 = unlimited)')),
                ('passing_score', models.DecimalField(decimal_places=2, default=70.0, help_text='Minimum score to pass (percentage)', max_digits=5)),
                ('randomize_questions', models.BooleanField(default=False)),
                ('randomize_choices', models.BooleanField(default=False)),
                ('questions_to_show', models.PositiveIntegerField(blank=True, help_text='Number of questions to show (null = all)', null=True)),
                ('show_correct_answers', models.BooleanField(default=True)),
                ('show_feedback', models.BooleanField(default=True)),
                ('show_score_immediately', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='content.activity')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessments_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'assessment',
                'verbose_name_plural': 'assessments',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('attempt_number', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('submitted', 'Submitted'), ('graded', 'Graded'), ('timed_out', 'Timed Out')], default='in_progress', max_length=20)),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('max_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('score_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('passed', models.BooleanField(blank=True, null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('graded_at', models.DateTimeField(blank=True, null=True)),
                ('time_spent_seconds', models.PositiveIntegerField(default=0)),
                ('feedback', models.TextField(blank=True)),
                ('questions_shown', models.JSONField(blank=True, default=list, help_text='IDs of questions shown in this attempt')),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='assessments.assessment')),
                ('enrollment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessment_attempts', to='content.enrollment')),
                ('graded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attempts_graded', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'assessment attempt',
                'verbose_name_plural': 'assessment attempts',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question_type', models.CharField(choices=[('multiple_choice', 'Multiple Choice'), ('multiple_select', 'Multiple Select'), ('true_false', 'True/False'), ('short_answer', 'Short Answer'), ('long_answer', 'Long Answer/Essay'), ('matching', 'Matching'), ('ordering', 'Ordering/Sequencing'), ('fill_blank', 'Fill in the Blank'), ('numeric', 'Numeric'), ('file_upload', 'File Upload')], default='multiple_choice', max_length=20)),
                ('text', models.TextField(help_text='The question text')),
                ('explanation', models.TextField(blank=True, help_text='Explanation shown after answering')),
                ('media_url', models.URLField(blank=True, max_length=500)),
                ('points', models.DecimalField(decimal_places=2, default=1.0, max_digits=5)),
                ('partial_credit', models.BooleanField(default=False, help_text='Allow partial credit for partially correct answers')),
                ('order', models.PositiveIntegerField(default=0)),
                ('outcome_tags', models.JSONField(blank=True, default=list, help_text='Learning outcomes this question assesses')),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=10)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='assessments.assessment')),
            ],
            options={
                'verbose_name': 'question',
                'verbose_name_plural': 'questions',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('is_correct', models.BooleanField(default=False)),
                ('points', models.DecimalField(blank=True, decimal_places=2, help_text='Points for selecting this choice (for partial credit)', max_digits=5, null=True)),
                ('feedback', models.TextField(blank=True, help_text='Feedback shown when this choice is selected')),
                ('order', models.PositiveIntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='assessments.question')),
            ],
            options={
                'verbose_name': 'choice',
                'verbose_name_plural': 'choices',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='MasteryEstimate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('outcome_tag', models.CharField(db_index=True, help_text='Learning outcome identifier', max_length=255)),
                ('mastery_level', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('confidence', models.DecimalField(decimal_places=2, default=0, help_text='Confidence in the estimate (0-100)', max_digits=5)),
                ('assessment_count', models.PositiveIntegerField(default=0, help_text='Number of assessments contributing to this estimate')),
                ('last_assessment_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('community', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mastery_estimates', to='communities.community')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mastery_estimates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'mastery estimate',
                'verbose_name_plural': 'mastery estimates',
                'ordering': ['-mastery_level'],
                'unique_together': {('user', 'outcome_tag', 'community')},
            },
        ),
        migrations.CreateModel(
            name='QuestionResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('response_data', models.JSONField(default=dict, help_text='User response data')),
                ('text_response', models.TextField(blank=True)),
                ('file_url', models.URLField(blank=True, max_length=500)),
                ('points_earned', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('is_correct', models.BooleanField(blank=True, null=True)),
                ('feedback', models.TextField(blank=True)),
                ('ai_feedback', models.TextField(blank=True, help_text='AI-generated feedback')),
                ('answered_at', models.DateTimeField(auto_now_add=True)),
                ('graded_at', models.DateTimeField(blank=True, null=True)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='assessments.assessmentattempt')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='assessments.question')),
            ],
            options={
                'verbose_name': 'question response',
                'verbose_name_plural': 'question responses',
                'ordering': ['question__order'],
                'unique_together': {('attempt', 'question')},
            },
        ),
    ]
