# Generated by Django 6.0 on 2025-12-15 23:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LRSConfiguration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('endpoint', models.URLField(max_length=500)),
                ('auth_type', models.CharField(choices=[('basic', 'Basic Auth'), ('oauth', 'OAuth 2.0')], default='basic', max_length=20)),
                ('username', models.CharField(blank=True, max_length=255)),
                ('password', models.CharField(blank=True, max_length=255)),
                ('oauth_client_id', models.CharField(blank=True, max_length=255)),
                ('oauth_client_secret', models.CharField(blank=True, max_length=255)),
                ('oauth_token_url', models.URLField(blank=True, max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
                ('xapi_version', models.CharField(default='1.0.3', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'LRS configuration',
                'verbose_name_plural': 'LRS configurations',
            },
        ),
        migrations.CreateModel(
            name='XAPIActivityType',
            fields=[
                ('id', models.CharField(help_text='Full IRI of the activity type', max_length=500, primary_key=True, serialize=False)),
                ('display_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('content', 'Content'), ('assessment', 'Assessment'), ('social', 'Social'), ('community', 'Community'), ('path', 'Learning Path')], default='content', max_length=50)),
                ('is_custom', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'xAPI activity type',
                'verbose_name_plural': 'xAPI activity types',
                'ordering': ['category', 'display_name'],
            },
        ),
        migrations.CreateModel(
            name='XAPIVerb',
            fields=[
                ('id', models.CharField(help_text='Full IRI of the verb', max_length=500, primary_key=True, serialize=False)),
                ('display_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('display_names', models.JSONField(default=dict, help_text='Language-tagged display names {"en": "completed", "es": "completado"}')),
                ('category', models.CharField(choices=[('learning', 'Learning Activities'), ('social', 'Social Actions'), ('assessment', 'Assessment'), ('ai', 'AI Interactions'), ('system', 'System Events')], default='learning', max_length=50)),
                ('is_custom', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'xAPI verb',
                'verbose_name_plural': 'xAPI verbs',
                'ordering': ['category', 'display_name'],
            },
        ),
        migrations.CreateModel(
            name='CMI5Package',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('package_key', models.CharField(help_text='Object key in MinIO for the package ZIP', max_length=500)),
                ('course_structure', models.JSONField(default=dict, help_text='Parsed cmi5.xml course structure')),
                ('publisher_id', models.CharField(blank=True, max_length=255)),
                ('publisher_name', models.CharField(blank=True, max_length=255)),
                ('version', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('uploading', 'Uploading'), ('processing', 'Processing'), ('ready', 'Ready'), ('error', 'Error')], default='uploading', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cmi5_packages_uploaded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'cmi5 package',
                'verbose_name_plural': 'cmi5 packages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CMI5AssignableUnit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('au_id', models.CharField(help_text='AU ID from cmi5.xml', max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('launch_url', models.URLField(max_length=500)),
                ('launch_method', models.CharField(choices=[('OwnWindow', 'Own Window'), ('AnyWindow', 'Any Window')], default='AnyWindow', max_length=20)),
                ('move_on', models.CharField(choices=[('Passed', 'Passed'), ('Completed', 'Completed'), ('CompletedAndPassed', 'Completed and Passed'), ('CompletedOrPassed', 'Completed or Passed'), ('NotApplicable', 'Not Applicable')], default='CompletedOrPassed', max_length=20)),
                ('mastery_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('activity', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cmi5_au', to='content.activity')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignable_units', to='xapi_integration.cmi5package')),
            ],
            options={
                'verbose_name': 'cmi5 assignable unit',
                'verbose_name_plural': 'cmi5 assignable units',
                'ordering': ['order'],
                'unique_together': {('package', 'au_id')},
            },
        ),
        migrations.CreateModel(
            name='CMI5Session',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('registration', models.UUIDField(db_index=True)),
                ('state', models.CharField(choices=[('initialized', 'Initialized'), ('launched', 'Launched'), ('completed', 'Completed'), ('abandoned', 'Abandoned'), ('waived', 'Waived'), ('terminated', 'Terminated')], default='initialized', max_length=20)),
                ('is_passed', models.BooleanField(blank=True, null=True)),
                ('is_completed', models.BooleanField(blank=True, null=True)),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('launched_at', models.DateTimeField(blank=True, null=True)),
                ('terminated_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('launch_token', models.CharField(max_length=255, unique=True)),
                ('token_expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignable_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='xapi_integration.cmi5assignableunit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cmi5_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'cmi5 session',
                'verbose_name_plural': 'cmi5 sessions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StatementQueue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('statement', models.JSONField(help_text='Full xAPI statement JSON')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('max_attempts', models.PositiveIntegerField(default=5)),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('next_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('lrs_statement_id', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('lrs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queued_statements', to='xapi_integration.lrsconfiguration')),
            ],
            options={
                'verbose_name': 'statement queue',
                'verbose_name_plural': 'statement queue',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['status', 'next_attempt_at'], name='xapi_integr_status_28f8f0_idx')],
            },
        ),
    ]
