# Generated by Django 6.0 on 2025-12-15 23:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('communities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsConnection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('backend_type', models.CharField(choices=[('clickhouse', 'ClickHouse'), ('postgresql', 'PostgreSQL')], default='clickhouse', max_length=20)),
                ('host', models.CharField(max_length=255)),
                ('port', models.PositiveIntegerField(default=8123)),
                ('database', models.CharField(max_length=100)),
                ('username', models.CharField(blank=True, max_length=100)),
                ('password', models.CharField(blank=True, max_length=255)),
                ('use_ssl', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_connected_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'analytics connection',
                'verbose_name_plural': 'analytics connections',
            },
        ),
        migrations.CreateModel(
            name='ETLJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('job_type', models.CharField(choices=[('lrs_to_clickhouse', 'LRS to ClickHouse'), ('aggregate_metrics', 'Aggregate Metrics'), ('custom', 'Custom ETL')], default='lrs_to_clickhouse', max_length=30)),
                ('schedule', models.CharField(blank=True, help_text='Cron expression for scheduled runs', max_length=100)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('last_run_status', models.CharField(blank=True, choices=[('success', 'Success'), ('failed', 'Failed'), ('partial', 'Partial')], max_length=20, null=True)),
                ('last_run_records', models.PositiveIntegerField(blank=True, null=True)),
                ('last_run_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'ETL job',
                'verbose_name_plural': 'ETL jobs',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MetricDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('display_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('engagement', 'Engagement'), ('participation', 'Participation'), ('learning', 'Learning Outcomes'), ('social', 'Social'), ('ai', 'AI Usage'), ('system', 'System')], default='engagement', max_length=30)),
                ('value_type', models.CharField(choices=[('count', 'Count'), ('percentage', 'Percentage'), ('duration', 'Duration'), ('score', 'Score'), ('rate', 'Rate')], default='count', max_length=20)),
                ('aggregation', models.CharField(choices=[('sum', 'Sum'), ('avg', 'Average'), ('min', 'Minimum'), ('max', 'Maximum'), ('count', 'Count'), ('count_distinct', 'Count Distinct')], default='count', max_length=20)),
                ('query_template', models.TextField(blank=True, help_text='SQL query template with placeholders')),
                ('scopes', models.JSONField(default=list, help_text='Available scopes: platform, community, group, user, activity, path')),
                ('supports_time_series', models.BooleanField(default=True)),
                ('default_time_range', models.CharField(choices=[('day', 'Day'), ('week', 'Week'), ('month', 'Month'), ('quarter', 'Quarter'), ('year', 'Year')], default='week', max_length=20)),
                ('format_string', models.CharField(blank=True, help_text='Python format string for display', max_length=50)),
                ('unit', models.CharField(blank=True, max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'metric definition',
                'verbose_name_plural': 'metric definitions',
                'ordering': ['category', 'display_name'],
            },
        ),
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('dashboard_type', models.CharField(choices=[('learner', 'Learner Dashboard'), ('facilitator', 'Facilitator Dashboard'), ('admin', 'Admin Dashboard'), ('community', 'Community Dashboard'), ('custom', 'Custom Dashboard')], default='custom', max_length=30)),
                ('layout', models.JSONField(default=dict, help_text='Grid layout configuration for widgets')),
                ('is_public', models.BooleanField(default=False)),
                ('allowed_roles', models.JSONField(default=list, help_text='Roles that can view this dashboard')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('community', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dashboards', to='communities.community')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dashboards_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'dashboard',
                'verbose_name_plural': 'dashboards',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ExportedReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('report_type', models.CharField(choices=[('dashboard_snapshot', 'Dashboard Snapshot'), ('custom_query', 'Custom Query'), ('scheduled_report', 'Scheduled Report')], default='dashboard_snapshot', max_length=30)),
                ('query', models.TextField(blank=True)),
                ('format', models.CharField(choices=[('csv', 'CSV'), ('xlsx', 'Excel'), ('pdf', 'PDF'), ('json', 'JSON')], default='csv', max_length=10)),
                ('file_key', models.CharField(blank=True, help_text='MinIO object key for the exported file', max_length=500)),
                ('file_size', models.PositiveIntegerField(blank=True, null=True)),
                ('time_range_start', models.DateTimeField(blank=True, null=True)),
                ('time_range_end', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='When the exported file will be deleted', null=True)),
                ('community', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exported_reports', to='communities.community')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_exported', to=settings.AUTH_USER_MODEL)),
                ('dashboard', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exports', to='analytics.dashboard')),
            ],
            options={
                'verbose_name': 'exported report',
                'verbose_name_plural': 'exported reports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DashboardWidget',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('widget_type', models.CharField(choices=[('metric', 'Single Metric'), ('line_chart', 'Line Chart'), ('bar_chart', 'Bar Chart'), ('pie_chart', 'Pie Chart'), ('table', 'Table'), ('leaderboard', 'Leaderboard'), ('progress', 'Progress Indicator'), ('activity_feed', 'Activity Feed')], default='metric', max_length=30)),
                ('config', models.JSONField(default=dict, help_text='Widget-specific configuration')),
                ('position_x', models.PositiveSmallIntegerField(default=0)),
                ('position_y', models.PositiveSmallIntegerField(default=0)),
                ('width', models.PositiveSmallIntegerField(default=1)),
                ('height', models.PositiveSmallIntegerField(default=1)),
                ('refresh_interval_seconds', models.PositiveIntegerField(default=0, help_text='Auto-refresh interval (0 = no auto-refresh)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dashboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='widgets', to='analytics.dashboard')),
                ('metrics', models.ManyToManyField(blank=True, related_name='widgets', to='analytics.metricdefinition')),
            ],
            options={
                'verbose_name': 'dashboard widget',
                'verbose_name_plural': 'dashboard widgets',
                'ordering': ['position_y', 'position_x'],
            },
        ),
    ]
