# Generated by Django 6.0 on 2025-12-15 23:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIAgent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('display_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('agent_type', models.CharField(choices=[('engagement_monitor', 'Engagement Monitor'), ('learning_recommender', 'Learning Recommender'), ('facilitator_assistant', 'Facilitator Assistant'), ('content_curator', 'Content Curator'), ('assessment_helper', 'Assessment Helper'), ('custom', 'Custom')], default='custom', max_length=30)),
                ('trigger_type', models.CharField(choices=[('scheduled', 'Scheduled'), ('event', 'Event-driven'), ('manual', 'Manual')], default='scheduled', max_length=20)),
                ('schedule', models.CharField(blank=True, help_text='Cron expression for scheduled agents', max_length=100)),
                ('trigger_events', models.JSONField(default=list, help_text='Events that trigger this agent')),
                ('config', models.JSONField(default=dict, help_text='Agent-specific configuration')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'AI agent',
                'verbose_name_plural': 'AI agents',
                'ordering': ['display_name'],
            },
        ),
        migrations.CreateModel(
            name='AICapability',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('display_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('capability_type', models.CharField(choices=[('generate_explanation', 'Generate Explanation'), ('generate_example', 'Generate Example'), ('summarize_discussion', 'Summarize Discussion'), ('summarize_content', 'Summarize Content'), ('classify_response', 'Classify Response'), ('generate_feedback', 'Generate Feedback'), ('answer_question', 'Answer Question'), ('generate_quiz', 'Generate Quiz Questions'), ('translate', 'Translate Content'), ('custom', 'Custom')], default='custom', max_length=30)),
                ('model_name', models.CharField(blank=True, max_length=100)),
                ('system_prompt', models.TextField(blank=True, help_text='System prompt template')),
                ('user_prompt_template', models.TextField(blank=True, help_text='User prompt template with {{variables}}')),
                ('use_rag', models.BooleanField(default=False)),
                ('rag_collection', models.CharField(blank=True, help_text='Qdrant collection to search', max_length=100)),
                ('rag_top_k', models.PositiveIntegerField(default=5)),
                ('temperature', models.DecimalField(decimal_places=2, default=0.7, max_digits=3)),
                ('max_tokens', models.PositiveIntegerField(default=1000)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'AI capability',
                'verbose_name_plural': 'AI capabilities',
                'ordering': ['display_name'],
            },
        ),
        migrations.CreateModel(
            name='AIProvider',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('provider_type', models.CharField(choices=[('openai', 'OpenAI'), ('anthropic', 'Anthropic'), ('azure_openai', 'Azure OpenAI'), ('custom', 'Custom')], default='openai', max_length=20)),
                ('api_endpoint', models.URLField(blank=True, max_length=500)),
                ('api_key_env_var', models.CharField(default='OPENAI_API_KEY', help_text='Environment variable name for API key', max_length=100)),
                ('default_chat_model', models.CharField(default='gpt-4-turbo-preview', max_length=100)),
                ('default_embedding_model', models.CharField(default='text-embedding-3-small', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
                ('requests_per_minute', models.PositiveIntegerField(default=60)),
                ('tokens_per_minute', models.PositiveIntegerField(default=100000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'AI provider',
                'verbose_name_plural': 'AI providers',
            },
        ),
        migrations.CreateModel(
            name='EmbeddingCollection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('display_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('qdrant_collection', models.CharField(max_length=100)),
                ('embedding_model', models.CharField(default='text-embedding-3-small', max_length=100)),
                ('embedding_dimensions', models.PositiveIntegerField(default=1536)),
                ('source_types', models.JSONField(default=list, help_text='Types of content in this collection')),
                ('document_count', models.PositiveIntegerField(default=0)),
                ('last_indexed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'embedding collection',
                'verbose_name_plural': 'embedding collections',
            },
        ),
        migrations.CreateModel(
            name='AgentRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('trigger_type', models.CharField(max_length=20)),
                ('trigger_event', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('actions_taken', models.JSONField(default=list, help_text='List of actions the agent took')),
                ('items_processed', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='ai_services.aiagent')),
            ],
            options={
                'verbose_name': 'agent run',
                'verbose_name_plural': 'agent runs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='aiagent',
            name='capabilities',
            field=models.ManyToManyField(blank=True, related_name='agents', to='ai_services.aicapability'),
        ),
        migrations.AddField(
            model_name='aicapability',
            name='provider',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='capabilities', to='ai_services.aiprovider'),
        ),
        migrations.CreateModel(
            name='AIInteraction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('interaction_type', models.CharField(choices=[('user_request', 'User Request'), ('agent_action', 'Agent Action'), ('system_task', 'System Task')], default='user_request', max_length=30)),
                ('community_id', models.UUIDField(blank=True, null=True)),
                ('activity_id', models.UUIDField(blank=True, null=True)),
                ('input_text', models.TextField(help_text='User query or agent input')),
                ('input_metadata', models.JSONField(blank=True, default=dict)),
                ('rag_documents_used', models.JSONField(default=list, help_text='IDs of documents used from RAG')),
                ('output_text', models.TextField(help_text='AI response')),
                ('output_metadata', models.JSONField(blank=True, default=dict)),
                ('model_used', models.CharField(blank=True, max_length=100)),
                ('prompt_tokens', models.PositiveIntegerField(default=0)),
                ('completion_tokens', models.PositiveIntegerField(default=0)),
                ('total_tokens', models.PositiveIntegerField(default=0)),
                ('latency_ms', models.PositiveIntegerField(default=0)),
                ('user_rating', models.PositiveSmallIntegerField(blank=True, help_text='User rating 1-5', null=True)),
                ('user_feedback', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('success', 'Success'), ('error', 'Error'), ('filtered', 'Filtered')], default='success', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interactions', to='ai_services.aiagent')),
                ('capability', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interactions', to='ai_services.aicapability')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_interactions', to=settings.AUTH_USER_MODEL)),
                ('provider', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interactions', to='ai_services.aiprovider')),
            ],
            options={
                'verbose_name': 'AI interaction',
                'verbose_name_plural': 'AI interactions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='ai_services_user_id_88c131_idx'), models.Index(fields=['capability', 'created_at'], name='ai_services_capabil_a5ca9e_idx')],
            },
        ),
        migrations.CreateModel(
            name='EmbeddingDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_type', models.CharField(choices=[('activity_content', 'Activity Content'), ('transcript', 'Transcript'), ('document', 'Document'), ('social_post', 'Social Post'), ('reflection', 'Learner Reflection'), ('policy', 'Policy Document')], max_length=50)),
                ('source_id', models.CharField(max_length=255)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('chunk_index', models.PositiveIntegerField(default=0)),
                ('chunk_text', models.TextField(help_text='The actual text chunk')),
                ('community_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('visibility', models.CharField(default='private', max_length=20)),
                ('qdrant_point_id', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='ai_services.embeddingcollection')),
            ],
            options={
                'verbose_name': 'embedding document',
                'verbose_name_plural': 'embedding documents',
                'indexes': [models.Index(fields=['source_type', 'source_id'], name='ai_services_source__95e92d_idx')],
            },
        ),
    ]
