# Generated by Django 6.0 on 2025-12-15 23:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('communities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('activity_type', models.CharField(choices=[('content', 'Content Viewing'), ('discussion', 'Discussion'), ('reflection', 'Reflection'), ('assignment', 'Assignment'), ('quiz', 'Quiz'), ('project', 'Project'), ('peer', 'Peer Activity'), ('cmi5', 'cmi5 Package')], default='content', max_length=20)),
                ('content_type', models.CharField(choices=[('mongodb', 'MongoDB Document'), ('minio', 'MinIO File'), ('cmi5', 'cmi5 Package'), ('external', 'External URL')], default='mongodb', max_length=20)),
                ('content_ref', models.CharField(blank=True, max_length=500)),
                ('estimated_minutes', models.PositiveIntegerField(blank=True, help_text='Estimated time to complete in minutes', null=True)),
                ('outcomes', models.JSONField(blank=True, default=list, help_text='Learning outcomes for this activity')),
                ('is_published', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities_created', to=settings.AUTH_USER_MODEL)),
                ('prerequisites', models.ManyToManyField(blank=True, related_name='unlocks', to='content.activity')),
            ],
            options={
                'verbose_name': 'activity',
                'verbose_name_plural': 'activities',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='LearningPath',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('cover_image_url', models.URLField(blank=True, max_length=500)),
                ('is_sequential', models.BooleanField(default=True, help_text='If true, activities must be completed in order')),
                ('estimated_hours', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('outcomes', models.JSONField(blank=True, default=list, help_text='Learning outcomes for completing this path')),
                ('is_published', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paths_created', to=settings.AUTH_USER_MODEL)),
                ('prerequisites', models.ManyToManyField(blank=True, related_name='unlocks', to='content.learningpath')),
            ],
            options={
                'verbose_name': 'learning path',
                'verbose_name_plural': 'learning paths',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('progress_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('last_activity_at', models.DateTimeField(blank=True, null=True)),
                ('community', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrollments', to='communities.community')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to=settings.AUTH_USER_MODEL)),
                ('path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='content.learningpath')),
            ],
            options={
                'verbose_name': 'enrollment',
                'verbose_name_plural': 'enrollments',
                'ordering': ['-enrolled_at'],
                'unique_together': {('user', 'path', 'community')},
            },
        ),
        migrations.CreateModel(
            name='ActivityProgress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='not_started', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('last_accessed_at', models.DateTimeField(blank=True, null=True)),
                ('total_time_seconds', models.PositiveIntegerField(default=0)),
                ('bookmark_position', models.JSONField(blank=True, default=dict, help_text='User position in the content for resuming')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='content.activity')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_progress', to=settings.AUTH_USER_MODEL)),
                ('enrollment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_progress', to='content.enrollment')),
            ],
            options={
                'verbose_name': 'activity progress',
                'verbose_name_plural': 'activity progress records',
                'ordering': ['-last_accessed_at'],
                'unique_together': {('user', 'activity', 'enrollment')},
            },
        ),
        migrations.CreateModel(
            name='CommunityPath',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_required', models.BooleanField(default=False)),
                ('available_from', models.DateTimeField(blank=True, null=True)),
                ('available_until', models.DateTimeField(blank=True, null=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paths_assigned', to=settings.AUTH_USER_MODEL)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_paths', to='communities.community')),
                ('path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_assignments', to='content.learningpath')),
            ],
            options={
                'verbose_name': 'community path',
                'verbose_name_plural': 'community paths',
                'ordering': ['-is_featured', '-added_at'],
                'unique_together': {('community', 'path')},
            },
        ),
        migrations.CreateModel(
            name='PathActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('section_title', models.CharField(blank=True, max_length=255)),
                ('section_order', models.PositiveIntegerField(default=0)),
                ('is_required', models.BooleanField(default=True)),
                ('unlock_conditions', models.JSONField(blank=True, default=dict, help_text='Conditions to unlock this activity (e.g., minimum score on previous)')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='path_memberships', to='content.activity')),
                ('path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='path_activities', to='content.learningpath')),
            ],
            options={
                'verbose_name': 'path activity',
                'verbose_name_plural': 'path activities',
                'ordering': ['section_order', 'order'],
                'unique_together': {('path', 'activity')},
            },
        ),
    ]
